name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP client
      run: sudo apt-get install ftp -y  # Install FTP client on Ubuntu

    - name: Deploy via FTP
      run: bash deploy.sh
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
